# This is a configuration file assuming the availability of an 80GiB GPU (A100 or H100).
# If you want to perform ensemble at each generation step, please ensure that the 'priority' for all models is set to 'supportive'. The threshold will be ignored.
NORM_TYPE_API_SERVER: 'average' # 'average' or 'score', 'score' means each model's output vector in the GaC ensemble is weighted by its score divided by the total score.
THRESHOLD_API_SERVER: 1.0
CONFIG_API_SERVER:
  - weight: '/data/share/model_weight/qwen/Qwen2.5-1.5B-Instruct/' # or 'upstage/SOLAR-10.7B-Instruct-v1.0'
    max_memory:
      0: '24GiB'
    device: 0
    num_gpus: 1
    name: 'qwen2.5-1.5b-instruct'
    score: 100
    priority: 'supportive'
    quantization: 'none' # 'none'/'8bit'/'4bit'
  
  # - weight: '/data/share/model_weight/qwen/Qwen2.5-Coder-1.5B-Instruct/' # or 'openchat/openchat-3.5-0106'
  #   max_memory:
  #     0: '24GiB'
  #   device: 1
  #   num_gpus: 1
  #   name: 'qwen2.5-coder-1.5b-instruct'
  #   score: 100
  #   priority: 'supportive'
  #   quantization: 'none' # 'none'/'8bit'/'4bit'
